version: "3.9"
services:
  db:
    build: 
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports:
      - '3306:3306'
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: frantiseksumsala/dp_sum0023
    ports:
      - 7080:80
      - 7443:443
      